name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - snapshot
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Run tests
      run: emacs -Q -batch -l ert -L . -L test/ -l test/output-tests.el -l test/query-tests.el -l test/parsing-tests.el -f ert-run-tests-batch-and-exit
